## Datatypes and Attributes

In [2]:
import numpy as np

In [3]:
a1= np.array([1,2,5])
a1

array([1, 2, 5])

In [4]:
type(a1)

numpy.ndarray

In [10]:
a3 = np.array([[[1, 2, 3.1],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12.7]],
               [[13, 14, 15],
                [16, 17, 18]]])
a3

array([[[ 1. ,  2. ,  3.1],
        [ 4. ,  5. ,  6. ]],

       [[ 7. ,  8. ,  9. ],
        [10. , 11. , 12.7]],

       [[13. , 14. , 15. ],
        [16. , 17. , 18. ]]])

In [6]:
a3.shape

(3, 2, 3)

In [8]:
a3.ndim

3

In [11]:
a3.dtype

dtype('float64')

In [12]:
a3.size

18

In [13]:
type(a3)

numpy.ndarray

In [16]:
a2 = np.array([[5,4,9],[6,5,4],[8,2,0]])

In [17]:
a2

array([[5, 4, 9],
       [6, 5, 4],
       [8, 2, 0]])

In [18]:
import pandas as pd

In [20]:
df = pd.DataFrame(a2)

In [21]:
df

0  1  2
0  5  4  9
1  6  5  4
2  8  2  0

In [23]:
once = np.ones((2,3))

In [24]:
once

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
zeros = np.zeros((2,3))

In [26]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
range_array=np.arange(0,10,2)

In [28]:
range_array

array([0, 2, 4, 6, 8])

In [29]:
random_array = np.random.randint(1,8, size=(3,5))

In [30]:
random_array

array([[7, 7, 7, 2, 7],
       [1, 1, 1, 2, 7],
       [2, 6, 2, 4, 5]])

In [31]:
random_array2=np.random.random((5,2))

In [32]:
random_array2

array([[0.49897727, 0.28984221],
       [0.3097791 , 0.72317994],
       [0.66139667, 0.70822502],
       [0.21276985, 0.92850787],
       [0.36208632, 0.54018818]])

In [34]:
random_array3=np.random.rand(5,2)

In [35]:
random_array3

array([[0.83144981, 0.48519033],
       [0.77628373, 0.73230866],
       [0.35745145, 0.07038973],
       [0.28716321, 0.97395727],
       [0.79731287, 0.25725077]])

In [ ]:
np.random.seed()